/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthedHomeRouteImport } from './routes/_authed/home'
import { Route as AuthedOutboxRouteImport } from './routes/_authed/outbox'
import { Route as AuthedDocumentsIndexRouteImport } from './routes/_authed/documents.index'
import { Route as AuthedDocumentsDocumentIdRouteImport } from './routes/_authed/documents.$documentId'
import { Route as AuthedDocumentsNewRouteImport } from './routes/_authed/documents.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedHomeRoute = AuthedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOutboxRoute = AuthedOutboxRouteImport.update({
  id: '/outbox',
  path: '/outbox',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDocumentsIndexRoute = AuthedDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDocumentsDocumentIdRoute =
  AuthedDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDocumentsNewRoute = AuthedDocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof AuthedHomeRoute
  '/outbox': typeof AuthedOutboxRoute
  '/documents/$documentId': typeof AuthedDocumentsDocumentIdRoute
  '/documents/new': typeof AuthedDocumentsNewRoute
  '/documents/': typeof AuthedDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof AuthedHomeRoute
  '/outbox': typeof AuthedOutboxRoute
  '/documents/$documentId': typeof AuthedDocumentsDocumentIdRoute
  '/documents/new': typeof AuthedDocumentsNewRoute
  '/documents': typeof AuthedDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/home': typeof AuthedHomeRoute
  '/_authed/outbox': typeof AuthedOutboxRoute
  '/_authed/documents/$documentId': typeof AuthedDocumentsDocumentIdRoute
  '/_authed/documents/new': typeof AuthedDocumentsNewRoute
  '/_authed/documents/': typeof AuthedDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/outbox'
    | '/documents/$documentId'
    | '/documents/new'
    | '/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/outbox'
    | '/documents/$documentId'
    | '/documents/new'
    | '/documents'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/home'
    | '/_authed/outbox'
    | '/_authed/documents/$documentId'
    | '/_authed/documents/new'
    | '/_authed/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/home': {
      id: '/_authed/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedHomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/outbox': {
      id: '/_authed/outbox'
      path: '/outbox'
      fullPath: '/outbox'
      preLoaderRoute: typeof AuthedOutboxRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/documents/': {
      id: '/_authed/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthedDocumentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/documents/$documentId': {
      id: '/_authed/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AuthedDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/documents/new': {
      id: '/_authed/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof AuthedDocumentsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedHomeRoute: typeof AuthedHomeRoute
  AuthedOutboxRoute: typeof AuthedOutboxRoute
  AuthedDocumentsDocumentIdRoute: typeof AuthedDocumentsDocumentIdRoute
  AuthedDocumentsNewRoute: typeof AuthedDocumentsNewRoute
  AuthedDocumentsIndexRoute: typeof AuthedDocumentsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedHomeRoute: AuthedHomeRoute,
  AuthedOutboxRoute: AuthedOutboxRoute,
  AuthedDocumentsDocumentIdRoute: AuthedDocumentsDocumentIdRoute,
  AuthedDocumentsNewRoute: AuthedDocumentsNewRoute,
  AuthedDocumentsIndexRoute: AuthedDocumentsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
