import type {
  ConfirmUploadRequest,
  DocumentFile,
  PresignDownloadResponse,
  PresignUploadRequest,
  PresignUploadResponse,
} from '@life-manager/shared'
import type { ActorContext } from '../../auth/actor.js'
import { db } from '../../db/client.js'
import { ConflictError, NotFoundError } from '../../lib/errors.js'
import { objectKeyFor, presignDownload, presignUpload } from '../../lib/storage.js'
import type { DocumentFileRow } from './documents.repository.js'
import * as repository from './documents.repository.js'

/**
 * File handling for Documents. domains/documents.md §4 rules 3, 4, 5, 10, 11 and §5's file
 * endpoints.
 *
 * Split out of `documents.service.ts` rather than added to it: the upload lifecycle is a distinct
 * state machine (presign → PUT to R2 → confirm) with its own failure modes, and one 600-line
 * service would bury the metadata rules that are the domain's actual subject. `documents.md` §10
 * lists this file.
 *
 * **Bytes never pass through here** (ADR-0008, conventions/api.md §9). This module hands out URLs
 * and records rows; the client talks to R2 directly.
 */

function toFile(row: DocumentFileRow): DocumentFile {
  return {
    id: row.id,
    document_id: row.documentId,
    version: row.version,
    mime: row.mime,
    size_bytes: row.sizeBytes,
    sha256: row.sha256 ?? '',
    is_primary: row.isPrimary,
    uploaded_at: row.uploadedAt === null ? null : row.uploadedAt.toISOString(),
    created_at: row.createdAt.toISOString(),
  }
}

/**
 * Confirms the document exists **and belongs to the actor's space**, returning its space id.
 *
 * Every file operation starts here. A missing or cross-space document is a 404 either way
 * (business rule 12, invariant 4), so a client cannot use the file endpoints to probe for
 * documents in another space — which would otherwise be a way around the whole tenant filter.
 */
async function requireDocumentSpace(actor: ActorContext, documentId: string): Promise<string> {
  const document = await repository.findById(actor, documentId)
  if (document === undefined) throw new NotFoundError('No such document.')
  return document.spaceId
}

/**
 * Step 1 of ADR-0008's transfer sequence: mint a PUT URL for one object.
 *
 * The row is inserted **before** the bytes exist, with `uploaded_at` null. That ordering is what
 * makes the flow recoverable: `file_id` is issued by us, so `:confirm` needs nothing but that id,
 * and an upload the client abandons leaves a row the sweep job can find (business rule 10) rather
 * than an untracked object in the bucket.
 *
 * Business rules 4 (server assigns `version`), 5 (API chooses the key), 11 (size and mime limits —
 * enforced by the Zod schema *and* signed into the URL, see `lib/storage.ts`).
 */
export async function presignUploadFor(
  actor: ActorContext,
  documentId: string,
  input: PresignUploadRequest,
): Promise<PresignUploadResponse> {
  const spaceId = await requireDocumentSpace(actor, documentId)

  const { fileId, version, storageKey } = await db.transaction(async (tx) => {
    // Inside the transaction so two concurrent presigns cannot pick the same version — the
    // unique index on (document_id, version) would reject the second, which is the correct
    // outcome but a worse error than serialising here.
    const nextVersion = await repository.nextVersion(actor, documentId, tx)

    // The key needs the file id, and the id is generated by the insert — so the row is inserted
    // with a placeholder key and updated, OR the id is generated here. Generating it here would
    // mean the API choosing a uuid outside the database, which is fine but inconsistent with
    // every other table. Insert-then-key keeps `gen_random_uuid()` as the single source of ids.
    const id = await repository.insertFile(
      actor,
      spaceId,
      {
        documentId,
        version: nextVersion,
        // Replaced immediately below, once the id exists. Never presigned or returned.
        storageKey: '',
        mime: input.mime,
        sizeBytes: input.size_bytes,
      },
      tx,
    )

    const key = objectKeyFor({ spaceId, documentId, fileId: id })
    await repository.setStorageKey(actor, id, key, tx)

    return { fileId: id, version: nextVersion, storageKey: key }
  })

  const presigned = await presignUpload({
    key: storageKey,
    mime: input.mime,
    sizeBytes: input.size_bytes,
  })

  return {
    file_id: fileId,
    upload_url: presigned.url,
    storage_key: storageKey,
    version,
    expires_at: presigned.expiresAt.toISOString(),
  }
}

/**
 * Step 4: the client reports that the bytes are in place.
 *
 * Business rule 3 — a new version becomes primary unless told otherwise, and the previous primary
 * is demoted **in the same transaction**. `document_files_one_primary_key` is a partial unique
 * index, so doing this in two transactions would either fail or leave a window with no primary.
 *
 * `409` on a file already confirmed (§5). Not idempotent-by-silence on purpose: a second confirm
 * means the client lost track of state, and `Idempotency-Key` is the mechanism for a *retried*
 * confirm (conventions/api.md §5) — which replays the first response rather than reaching here.
 */
export async function confirmUpload(
  actor: ActorContext,
  documentId: string,
  input: ConfirmUploadRequest,
  options: { makePrimary?: boolean } = {},
): Promise<DocumentFile> {
  await requireDocumentSpace(actor, documentId)

  const file = await repository.findFile(actor, documentId, input.file_id)
  if (file === undefined) throw new NotFoundError('No such file.')
  if (file.uploadedAt !== null) throw new ConflictError('That file has already been confirmed.')

  const makePrimary = options.makePrimary ?? true

  await db.transaction(async (tx) => {
    const changed = await repository.confirmFile(
      actor,
      input.file_id,
      { sha256: input.sha256 ?? null },
      tx,
    )
    if (changed === 0) throw new NotFoundError('No such file.')

    if (makePrimary) {
      await repository.demoteAllPrimary(actor, documentId, tx)
      await repository.setPrimary(actor, input.file_id, tx)
    }
  })

  const confirmed = await repository.findFile(actor, documentId, input.file_id)
  if (confirmed === undefined) throw new NotFoundError('No such file.')
  return toFile(confirmed)
}

/** Mirror image of the upload presign — a GET URL for one object (ADR-0008). */
export async function presignDownloadFor(
  actor: ActorContext,
  documentId: string,
  fileId: string,
): Promise<PresignDownloadResponse> {
  await requireDocumentSpace(actor, documentId)

  const file = await repository.findFile(actor, documentId, fileId)
  if (file === undefined) throw new NotFoundError('No such file.')

  // An unconfirmed row has no bytes behind it. Presigning anyway would hand the client a URL
  // that 404s at R2, which looks like a storage fault rather than a state error.
  if (file.uploadedAt === null) {
    throw new ConflictError('That upload was never confirmed, so there is nothing to download.')
  }

  const presigned = await presignDownload({ key: file.storageKey, mime: file.mime })

  return {
    download_url: presigned.url,
    expires_at: presigned.expiresAt.toISOString(),
  }
}

/** `PATCH /documents/:id/files/:fileId` — promotion to primary, business rule 3. */
export async function makePrimary(
  actor: ActorContext,
  documentId: string,
  fileId: string,
): Promise<DocumentFile> {
  await requireDocumentSpace(actor, documentId)

  const file = await repository.findFile(actor, documentId, fileId)
  if (file === undefined) throw new NotFoundError('No such file.')
  if (file.uploadedAt === null) {
    throw new ConflictError('An unconfirmed file cannot be made primary.')
  }

  await db.transaction(async (tx) => {
    await repository.demoteAllPrimary(actor, documentId, tx)
    await repository.setPrimary(actor, fileId, tx)
  })

  const updated = await repository.findFile(actor, documentId, fileId)
  if (updated === undefined) throw new NotFoundError('No such file.')
  return toFile(updated)
}

/**
 * Soft-deletes one file version.
 *
 * **The R2 object is deliberately left in place** (business rule 9, conventions/data.md §3,
 * ADR-0008): object cleanup is a separate job so an accidental delete stays recoverable. If the
 * deleted file was primary, the newest remaining confirmed version is promoted — a document with
 * files but no primary would render as having no file at all, which is a worse outcome than
 * picking the obvious successor.
 */
export async function removeFile(
  actor: ActorContext,
  documentId: string,
  fileId: string,
): Promise<void> {
  await requireDocumentSpace(actor, documentId)

  const file = await repository.findFile(actor, documentId, fileId)
  if (file === undefined) throw new NotFoundError('No such file.')

  await db.transaction(async (tx) => {
    const changed = await repository.softDeleteFile(actor, fileId, tx)
    if (changed === 0) throw new NotFoundError('No such file.')

    if (!file.isPrimary) return

    const remaining = (await repository.listFiles(actor, documentId, tx)).filter(
      (candidate) => candidate.id !== fileId && candidate.uploadedAt !== null,
    )
    const successor = remaining[remaining.length - 1]
    if (successor !== undefined) await repository.setPrimary(actor, successor.id, tx)
  })
}

export async function listFiles(actor: ActorContext, documentId: string): Promise<DocumentFile[]> {
  await requireDocumentSpace(actor, documentId)
  const rows = await repository.listFiles(actor, documentId)
  return rows.map(toFile)
}
